use actix_files::Files;
use actix_web::web;

use crate::handlers::*;

pub(crate) fn configure(cfg: &mut web::ServiceConfig) {
    cfg.service(summary)
        .service(overview)
        .service(auth_context)
        .service(login)
        .service(list_audit_events)
        .service(entity_detail)
        .service(list_evidence)
        .service(upload_evidence)
        .service(archive_entity)
        .service(list_stats)
        .service(phone_matrix)
        .service(phone_matrix_detail)
        .service(phone_matrix_assumption_list)
        .service(phone_matrix_recalculate)
        .service(update_stats)
        .service(workspace_dashboard)
        .service(run_area_action)
        .service(list_workspace_templates)
        .service(create_workspace_template)
        .service(update_workspace_template)
        .service(update_workspace_template_status)
        .service(reorder_workspace_template)
        .service(list_workspace_template_versions)
        .service(apply_workspace_template)
        .service(ops_status_fragment)
        .service(workspace_activity_fragment)
        .service(list_organizations)
        .service(create_organization)
        .service(list_projects)
        .service(create_project)
        .service(list_site_profiles)
        .service(create_site_profile)
        .service(update_site_profile)
        .service(list_survey_campaigns)
        .service(create_survey_campaign)
        .service(update_survey_campaign_status)
        .service(list_assets)
        .service(signal_probe_dashboard)
        .service(area_dossier)
        .service(create_asset)
        .service(update_asset)
        .service(update_asset_status)
        .service(list_reports)
        .service(create_report)
        .service(update_report)
        .service(list_alerts)
        .service(create_alert)
        .service(update_alert_status)
        .service(list_tickets)
        .service(create_ticket)
        .service(update_ticket_status)
        .service(list_iot_readings)
        .service(create_iot_reading)
        .service(imei_compliance_summary)
        .service(ingest_imei_event)
        .service(priority_zones)
        .service(decision_report)
        .service(decision_board)
        .service(list_decision_snapshots)
        .service(create_decision_snapshot)
        .service(update_decision_status)
        .service(list_execution_plans)
        .service(execution_board)
        .service(create_execution_plan_from_decision)
        .service(update_execution_plan_status)
        .service(export_assets)
        .service(export_tickets)
        .service(export_priority_zones)
        .service(export_phone_matrix)
        .service(Files::new("/static", "static").show_files_listing())
        .default_service(web::get().to(|| async {
            actix_web::HttpResponse::Found()
                .append_header(("Location", "/static/index.html"))
                .finish()
        }));
}
